### PR TITLE
readme.md: correct package listing for Ubuntu

### PR DESCRIPTION
**Pull request by megahall**
On Debian and Ubuntu, `python-crypto` is required, not `python-pycryptopp`.

I suspect the README depended on a pre-existing install of `python-crypto`.

### CODE REVIEW

**Comment by megahall** [comment]
Ping

**Comment by smeinecke** [comment]
As far as I know, there is no plan to continue development on this project by ICANN.

I already wrote to ICANN about this:

```
Unfortunately, the API was created by our web developers but it is not something
they support on an ongoing basis.  ICANN also does not support this.
```

**Comment by megahall** [comment]
## Ouch! Thanks for informing me!

**Comment by marktheunissen** [comment]
@rupl @elliotttf Anyone at 4K working on these tools?

**Comment by elliotttf** [comment]
@marktheunissen not that I'm aware of. I'm happy to merge this though if it's useful.

**Comment by marktheunissen** [comment]
@elliotttf There are a couple of PRs. Just wondering.

**Pull request merged**
